public class Run4_threadCreateException3 {
    public static void main(String[] args) {
        Thread1.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            public void uncaughtException(Thread t, Throwable e) {
                System.out.println("线程:" + t.getName() + " 出现了异常：");
                e.printStackTrace();
            }
        });
        Thread1 t1 = new Thread1();
        t1.setName("thread t1");
